## Model optimization / futher model versions

- Linear Regression
- Polynomial Regression
- K-Nearest-Neighbors Regression
- Regression Trees / Decision Tree Regresison
- Support Vector Regression

In [32]:
# importing libraries
import pandas as pd
from sklearn import linear_model
import numpy as np
from sklearn.impute import SimpleImputer
from sklearn.metrics import mean_absolute_error
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import PowerTransformer

In [33]:
train_data = pd.read_csv('new_traindata.csv')
test_data = pd.read_csv('new_testdata.csv')

In [34]:
train_data.head()

,instant,season,yr,mnth,holiday,weekday,workingday,weathersit,atemp,windspeed,leaflets,price reduction,cnt
0,154,2.0,0,6,0,0,1,1,0.587133,0.161118,991,0,5312
1,685,4.0,1,11,0,6,1,2,0.324492,0.114392,601,0,5445
2,368,1.0,1,1,0,1,1,1,0.126275,0.198321,549,0,2236
3,472,2.0,1,4,1,0,0,1,0.614925,0.172953,740,0,6370
4,442,1.0,1,3,0,1,0,2,0.505046,0.089160,773,1,7836

In [35]:
test_data.head()

,instant,season,yr,mnth,holiday,weekday,workingday,weathersit,atemp,windspeed,leaflets,price reduction,cnt
0,299,4.0,0,10,0,2,1,2,0.472846,0.120161,605,0,3894
1,458,2.0,1,4,0,0,1,1,0.427513,0.206779,518,0,5936
2,687,4.0,1,11,0,1,0,1,0.326383,0.139545,766,0,5629
3,346,4.0,0,12,0,2,1,1,0.270196,0.057694,739,0,3310
4,291,4.0,0,10,0,1,1,2,0.522721,0.093734,463,0,4748

In [36]:
train_features = train_data.iloc[:, :-1]
train_labels = train_data.iloc[:, -1:]

test_features = test_data.iloc[:, :-1]
test_labels = test_data.iloc[:, -1:]

### Model building